on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  publish:
    runs-on: ubuntu-latest
    needs: test
#    if: "${{ env.GITHUB_REF == 'refs/heads/main' }}"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Publish
        run: npm publish
